/*
 * okctl-metrics-backend
 *
 * A service for collecting metrics in okctl
 *
 * API version: 0.0.1
 * Contact: okctl@oslo.kommune.no
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	_ "embed"
	"fmt"

	"github.com/oslokommune/okctl-metrics-service/pkg/config"

	sw "github.com/oslokommune/okctl-metrics-service/pkg/router"

	"github.com/sirupsen/logrus"
)

//go:embed specification.yaml
var specification []byte

func main() {
	cfg, err := config.Generate()
	if err != nil {
		panic(err.Error())
	}

	err = cfg.Validate()
	if err != nil {
		panic(err.Error())
	}

	logger := logrus.New()
	logger.SetFormatter(&logrus.JSONFormatter{})
	logger.SetLevel(cfg.LogLevel)

	logger.Info("Server started")

	router, teardownFn := sw.New(cfg, logger, specification)
	defer teardownFn()

	logger.Fatal(router.Run(fmt.Sprintf(":%d", cfg.Port)))
}
