name: CD

on:
  push:
    branches: [ main ]
    paths:
      - pkg/**
      - main.go
      - Dockerfile

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.16'

    - run: make check

    - name: Github Tag Bump
      id: bump_version
      uses: anothrNick/github-tag-action@1.36.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEFAULT_BUMP: patch
        RELEASE_BRANCHES: main
        WITH_V: true

    - run: echo "image_registry=ghcr.io/oslokommune" >> $GITHUB_ENV
    - run: echo "image_name=okctl-metrics-service" >> $GITHUB_ENV
    - run: echo "image_version=$(git tag | sort -V | tail -1)" >> $GITHUB_ENV
    - run: echo "image_uri=${{ env.image_registry }}/${{ env.image_name}}:${{ env.image_version}}" >> $GITHUB_ENV
    
    - name: Build the Docker image
      run: docker build --tag ${{ env.image_uri }} .

    - name: Login to GitHub Packages Docker Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push Docker image
      run: docker push ${{ env.image_uri }}

    - name: Repository Dispatch
      # You may pin to the exact commit or the version.
      # uses: peter-evans/repository-dispatch@ce5485de42c9b2622d2ed064be479e8ed65e76f4
      uses: peter-evans/repository-dispatch@v1.1.3
      with:
        # A repo scoped GitHub Personal Access Token
        token: ${{ secrets.OKCTL_INFRASTRUCTURE_DISPATCH_PAT }}
        # The full name of the repository to send the dispatch.
        repository: oslokommune/okctl-infrastructure
        # A custom webhook event name.
        event-type: new-release
        # JSON payload with extra information about the webhook event that your action or worklow may use.
        client-payload: '{"name": "okctl-metrics-service", "version": "${{ env.image_version }}"}'
